# Generated by Django 3.1.7 on 2021-06-02 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_delete_dominantemotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataaboutuserandvideo',
            name='ID_screenshot',
        ),
    ]
