# Generated by Django 3.1.7 on 2021-06-03 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_remove_dataaboutuserandvideo_id_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.dataaboutuserandvideo'),
        ),
    ]
