# Generated by Django 3.1.7 on 2021-06-03 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DB', '0004_auto_20210603_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataaboutuserandvideo',
            name='ID_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataaboutuserandvideo',
            name='ID_video_information',
            field=models.CharField(max_length=80),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
