# Generated by Django 3.1.7 on 2021-06-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0006_auto_20210603_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataaboutuserandvideo',
            name='time_emo',
            field=models.TimeField(max_length=40, null=True),
        ),
    ]
